[package]
name = "local-gradient"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rufi = { version = "0.2.0", features = ["core", "programs"] }