[package]
name = "rufi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["core", "distributed"]
full = ["core", "distributed"]
core = []
distributed = []

[dependencies]
rf-core = { version = "0.3.0", path = "../rf-core" }
rf-distributed = { version = "0.1.0", path = "../rf-distributed" }
